version: "3.2"

services:
    docker-adonis-api:
        build: 
            context: ./docker/adonis
        container_name: docker-adonis-api
        ports:
            - "1379:3333"
        volumes:
            - ./:/home/jackson/study/crm-adonis-api
            - /usr/app/node_modules
        networks:
            - network
        depends_on: 
            - docker-adonis-mysql

    docker-adonis-mysql:
        image: mysql:8
        command: --default-authentication-plugin=mysql_native_password
        container_name: docker-adonis-mysql
        volumes:
            - ./data/mysql:/var/lib/mysql
        ports:
            - 3300:3306
        environment:
            MYSQL_ROOT_PASSWORD: P2ssW0rD
            MYSQL_DATABASE: adonis-mysql
        networks:
            - network 

networks:
    network:
        driver: bridge